
spring:
  datasource:
    url: jdbc:mysql://47.107.71.52:3306/sign?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/sign?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#    password: root
    driverclassname: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:static/,file:static/
#    db-name: guns #用来搜集数据库的所有表
#    filters: wall,mergeStat
# TODO xml文件放在mapper/mapping文件夹下，无法映射
#mybatis-plus:
#  mapper-locations: classpath*:com/jingli/mapper/mapping/*.xml

# 代码生成器
code:
  dirPath: D:\project\sign\src\main\java # 生成需要改此路径
  author: jingli
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://47.107.71.52:3306/sign?useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#  url: jdbc:mysql://127.0.0.1:3306/sign?useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  username: root
  password: 123456
#  password: root
  includetable: announcement # "user_dept","course_table","sign","sign_record","take_leave" #多个逗号隔开user,
  parentpackage: com.jingli.modular # 生成需要改此路径
  openLombok: true

#多环境配置
---
server:
  port: 80
spring:
  profiles: prod
#  profiles:
#    active: prod
---
server:
  port: 8088
spring:
  profiles:
    active: dev
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: /WEB-INF/view/
#  profiles: dev

